title: Zhumingjun's Homepage
page-top-title: Zhu-mingjun
top-section-bg-text: Fortune favors the bold, and a fresh start awaits them.
home-subtitle: Zhu-mingjun&ensp;|&ensp;朱明君
copyright-text: '&copy; Zhumingjun 2023-2025. All Rights Reserved.'
